const Question = require('../models/Question');
const Result = require('../models/Result');
const axios = require('axios');
const Groq = require('groq-sdk');

// @desc    Get all questions
// @route   GET /api/exams/questions
// @access  Public
const getQuestions = async (req, res) => {
    try {
        console.log('🔍 Fetching all questions from DB...');
        const questions = await Question.find();
        console.log(`📡 Returning ${questions.length} questions to client`);
        res.json(questions);
    } catch (err) {
        console.error('❌ Error fetching questions:', err.message);
        res.status(500).json({ message: err.message });
    }
};

// @desc    Submit exam result
// @route   POST /api/exams/submit
// @access  Public
const submitResult = async (req, res) => {
    const result = new Result({
        candidateName: req.body.candidateName,
        score: req.body.score,
        totalQuestions: req.body.totalQuestions,
        answers: req.body.answers,
        violations: req.body.violations,
    });

    try {
        const newResult = await result.save();
        res.status(201).json(newResult);
    } catch (err) {
        res.status(400).json({ message: err.message });
    }
};

// @desc    Generate resume-specific questions using AI
// @route   POST /api/exams/generate
// @access  Public
const generateQuestions = async (req, res) => {
    console.log('🚀 Dynamic Question Generation Triggered');
    try {
        const { analysisData } = req.body;

        if (!analysisData) {
            console.log('❌ Error: Missing analysisData in request body');
            return res.status(400).json({ message: 'Missing resume analysis data' });
        }

        console.log('📊 Received Analysis Data:', JSON.stringify(analysisData).substring(0, 200) + '...');
        console.log(`🛠 Skills: ${analysisData.skills?.length || 0}, Projects: ${analysisData.projects?.length || 0}`);

        const systemPrompt = `
You are a Senior Technical Interviewer. 
Your goal is to rigorously test a candidate based on their resume data.

DIFFICULTY LEVEL: HARD / ADVANCED
- Do NOT ask basic "What is X" questions.
- Each question should require deep technical understanding or problem-solving.

QUESTION MIX (Total 15 questions):
1. 40% Project-Specific: Deep dives into the architecture or choices made in their projects.
2. 40% Skill-Specific: Advanced concepts for their listed expert skills (Python, Java, etc.).
3. 20% Logic & Syntax: Challenging code snippets for debugging or logic puzzles.

STRICT JSON OUTPUT FORMAT:
[
  {
    "question": "Challenging technical question here",
    "options": ["Option 0", "Option 1", "Option 2", "Option 3"],
    "type": "mcq | logic | syntax",
    "correctAnswer": 0,
    "skill": "Specific Skill Name",
    "difficulty": "advanced"
  }
]

Candidate Data:
${JSON.stringify(analysisData, null, 2)}

RETURN ONLY THE JSON ARRAY. NO PREAMBLE.`;

        console.log('🤖 Sending prompt to Ollama...');
        const ollamaResponse = await axios.post('http://localhost:11434/api/generate', {
            model: 'llama3',
            prompt: systemPrompt,
            stream: false,
            format: 'json'
        });

        console.log('🤖 Ollama responded.');
        const rawResponse = ollamaResponse.data.response;

        let questions;
        try {
            // Find the first [ and last ] to extract the JSON array
            const startIndex = rawResponse.indexOf('[');
            const endIndex = rawResponse.lastIndexOf(']');

            if (startIndex === -1 || endIndex === -1) {
                console.error('❌ No JSON array found in AI response');
                console.log('Raw Response:', rawResponse);
                return res.status(500).json({ message: 'AI failed to return a JSON array' });
            }

            const jsonStr = rawResponse.substring(startIndex, endIndex + 1);
            questions = JSON.parse(jsonStr);

            console.log(`✅ Successfully generated and parsed ${questions.length} questions`);
        } catch (parseErr) {
            console.error('❌ JSON Parse Error:', parseErr.message);
            console.log('Raw Response Snippet:', rawResponse.substring(0, 500));
            return res.status(500).json({ message: `AI format error: ${parseErr.message}` });
        }

        if (!Array.isArray(questions) || questions.length === 0) {
            console.warn('⚠️ AI returned empty or non-array result');
            return res.status(500).json({ message: 'No questions generated by AI' });
        }

        // Clear and save
        console.log('🧹 Clearing old questions...');
        await Question.deleteMany({});

        console.log('💾 Saving new questions...');
        const savedQuestions = await Question.insertMany(questions);

        console.log(`🎉 Successfully saved ${savedQuestions.length} questions to database.`);
        res.status(201).json({
            message: 'Questions generated successfully',
            count: savedQuestions.length,
            questions: savedQuestions
        });

    } catch (err) {
        console.error('❌ Question Generation Error:', err.stack);
        res.status(500).json({ message: err.message || 'Error generating questions' });
    }
};

const getAssessmentSkillNames = (assessmentContext) => (
    Array.isArray(assessmentContext?.skills)
        ? assessmentContext.skills.filter(Boolean)
        : []
);

const getResumeSkillNames = (resumeData) => (
    Array.isArray(resumeData.skills)
        ? resumeData.skills
            .map((skill) => skill?.name || skill?.skill || skill?.category)
            .filter(Boolean)
        : []
);

const buildPhase2FallbackQuestions = (resumeData, assessmentContext) => {
    const assessmentSkills = getAssessmentSkillNames(assessmentContext);
    const resumeSkills = getResumeSkillNames(resumeData);
    const projects = Array.isArray(resumeData.projects) ? resumeData.projects.slice(0, 3) : [];
    const primarySkill = assessmentSkills[0] || resumeSkills[0] || 'JavaScript';
    const secondarySkill = assessmentSkills[1] || resumeSkills[1] || 'React';
    const primaryProject = assessmentContext?.title || projects[0]?.name || 'your main project';
    const projectTechs = projects[0]?.technologies?.slice(0, 3).join(', ') || primarySkill;

    return [
        {
            id: 'phase2_1',
            type: 'syntax',
            title: `${primarySkill} syntax correction`,
            question: `Fix the syntax issues in a ${primarySkill} function related to ${primaryProject}. Explain what was broken and why your version works.`,
            skill: primarySkill,
            difficulty: 'advanced',
            starterCode: `function buildSummary(skill, project) {\n  const label = skill + ' for ' + project\n  return { label: label, ready: true\n}\n`,
            evaluationPoints: [
                'Correct syntax and balanced braces',
                'Clear explanation of the issue',
                'Readable final code'
            ],
            expectedApproach: 'Repair the broken function, return a valid object, and explain the syntax mistakes.'
        },
        {
            id: 'phase2_2',
            type: 'logic',
            title: `${secondarySkill} state logic`,
            question: `A candidate dashboard built with ${secondarySkill} is updating the wrong card after each API response. Describe the likely logic bug and write corrected logic.`,
            skill: secondarySkill,
            difficulty: 'advanced',
            starterCode: `const nextCards = cards.map((card, index) => {\n  if (index = selectedIndex) {\n    card.status = response.status;\n  }\n  return card;\n});`,
            evaluationPoints: [
                'Identify assignment vs comparison bug',
                'Avoid mutating existing state directly',
                'Return corrected update logic'
            ],
            expectedApproach: 'Explain why the condition is wrong and produce an immutable update.'
        },
        {
            id: 'phase2_3',
            type: 'coding',
            title: `${primaryProject} feature writing`,
            question: `Write a small function for ${primaryProject} that validates user input before submission. Use ideas relevant to ${projectTechs}.`,
            skill: primarySkill,
            difficulty: 'advanced',
            starterCode: `// Write a validateSubmission function here\n`,
            evaluationPoints: [
                'Covers required and invalid values',
                'Readable logic with useful return shape',
                'Practical for real project usage'
            ],
            expectedApproach: 'Write a utility that returns validation errors or a success result.'
        },
        {
            id: 'phase2_4',
            type: 'syntax',
            title: 'Async syntax review',
            question: `Correct the async syntax below and explain how the flow should behave in production code.`,
            skill: primarySkill,
            difficulty: 'advanced',
            starterCode: `async function loadCandidate() {\n  const response = await fetch('/api/candidate')\n  const data = response.json();\n  if (!response.ok) {\n    throw 'Failed to load'\n  }\n  return data;\n`,
            evaluationPoints: [
                'Close the function correctly',
                'Await JSON parsing correctly',
                'Use safer error handling'
            ],
            expectedApproach: 'Return valid async code and improve the thrown error.'
        },
        {
            id: 'phase2_5',
            type: 'logic',
            title: `${primaryProject} bug analysis`,
            question: `In ${primaryProject}, duplicate records appear after refresh. Explain the likely logic issue and write a safer merge strategy.`,
            skill: secondarySkill,
            difficulty: 'advanced',
            starterCode: `const merged = [...existingItems, ...incomingItems];`,
            evaluationPoints: [
                'Identify why duplicates appear',
                'Use a stable key or map-based merge',
                'Explain tradeoffs briefly'
            ],
            expectedApproach: 'Describe the duplication issue and provide deduplication logic.'
        },
        {
            id: 'phase2_6',
            type: 'coding',
            title: `${primarySkill} problem solving`,
            question: `Write a reusable helper that groups resume skills by category and sorts each group by proficiency.`,
            skill: primarySkill,
            difficulty: 'advanced',
            starterCode: `const skills = [\n  { name: 'React', category: 'Frontend', proficiency: 'Advanced' },\n  { name: 'Node.js', category: 'Backend', proficiency: 'Intermediate' }\n];\n\n// Write your helper below\n`,
            evaluationPoints: [
                'Correct grouping output',
                'Stable proficiency ordering',
                'Readable implementation'
            ],
            expectedApproach: 'Group by category and sort using a proficiency ranking map.'
        }
    ];
};

const normalizePhase2Questions = (questions) => {
    if (!Array.isArray(questions)) {
        return [];
    }

    return questions.map((question, index) => ({
        id: question.id || `phase2_${index + 1}`,
        type: ['syntax', 'logic', 'coding'].includes(question.type) ? question.type : 'logic',
        title: question.title || `Question ${index + 1}`,
        question: question.question || 'Explain your solution.',
        skill: question.skill || 'General',
        difficulty: ['basic', 'intermediate', 'advanced'].includes(question.difficulty)
            ? question.difficulty
            : 'advanced',
        starterCode: question.starterCode || '',
        evaluationPoints: Array.isArray(question.evaluationPoints) ? question.evaluationPoints : [],
        expectedApproach: question.expectedApproach || ''
    }));
};

const generatePhase2Questions = async (req, res) => {
    try {
        const { resumeData, assessmentContext } = req.body;

        if (!resumeData) {
            return res.status(400).json({ message: 'Missing resume data' });
        }

        const groqKey = process.env.GROQ_API_KEY;
        if (!groqKey) {
            return res.json({
                source: 'fallback',
                questions: buildPhase2FallbackQuestions(resumeData, assessmentContext)
            });
        }

        const requiredSkillNames = getAssessmentSkillNames(assessmentContext);
        const resumeSkills = Array.isArray(resumeData.skills) ? resumeData.skills.slice(0, 8) : [];
        const skills = requiredSkillNames.length > 0
            ? requiredSkillNames.map((skill) => ({
                name: skill,
                category: 'Job Requirement',
                proficiency: 'Required'
            }))
            : resumeSkills;
        const projects = Array.isArray(resumeData.projects) ? resumeData.projects.slice(0, 4) : [];
        const experiences = Array.isArray(resumeData.experiences) ? resumeData.experiences.slice(0, 2) : [];

        const prompt = `Generate 8 advanced Phase 2 assessment questions for a coding interview.

Candidate resume data:
${JSON.stringify({
            name: resumeData.name,
            summary: resumeData.summary,
            resumeSkills,
            projects,
            experiences
        }, null, 2)}

Assessment context:
${JSON.stringify({
            roleTitle: assessmentContext?.title || null,
            requiredSkills: requiredSkillNames
        }, null, 2)}

Rules:
- Question types must be a mix of "syntax", "logic", and "coding".
- These are written-answer questions, not MCQ.
- If requiredSkills are provided, prioritize those job-required skills for question selection.
- Use resume projects and experience to make the scenarios realistic.
- Focus on debugging, syntax correction, code reasoning, and writing small real-world functions.
- Keep each question practical and job-relevant.
- Include starterCode when code review or code writing would help.
- difficulty must be "advanced" unless the resume is very junior, then "intermediate".

Return ONLY valid JSON in this exact format:
[
  {
    "id": "phase2_1",
    "type": "syntax",
    "title": "Short title",
    "question": "Full written-answer question",
    "skill": "React",
    "difficulty": "advanced",
    "starterCode": "optional code snippet",
    "evaluationPoints": ["point 1", "point 2", "point 3"],
    "expectedApproach": "brief interviewer guidance"
  }
]
`;

        const groq = new Groq({ apiKey: groqKey });
        const completion = await groq.chat.completions.create({
            model: 'llama-3.3-70b-versatile',
            temperature: 0.4,
            max_tokens: 2500,
            messages: [
                {
                    role: 'system',
                    content: 'You are a senior technical interviewer. Return valid JSON only.'
                },
                {
                    role: 'user',
                    content: prompt
                }
            ]
        });

        let responseText = completion.choices[0]?.message?.content || '[]';
        responseText = responseText.replace(/```json\n?|\n?```/g, '').trim();

        const parsed = JSON.parse(responseText);
        const normalizedQuestions = normalizePhase2Questions(parsed);

        if (normalizedQuestions.length === 0) {
            return res.json({
                source: 'fallback',
                questions: buildPhase2FallbackQuestions(resumeData, assessmentContext)
            });
        }

        res.json({
            source: 'groq',
            questions: normalizedQuestions
        });
    } catch (err) {
        console.error('Phase 2 generation error:', err);
        res.json({
            source: 'fallback',
            questions: buildPhase2FallbackQuestions(req.body.resumeData || {}, req.body.assessmentContext)
        });
    }
};

const seedQuestions = async (req, res) => {
    const sampleQuestions = [
        {
            question: 'What is React primarily used for?',
            options: ['Backend development', 'Building user interfaces', 'Database management', 'Server configuration'],
            type: 'mcq',
            correctAnswer: 1
        },
        {
            question: 'Which hook is used for side effects in React?',
            options: ['useState', 'useEffect', 'useContext', 'useReducer'],
            type: 'mcq',
            correctAnswer: 1
        },
        {
            question: 'What does JSX stand for?',
            options: ['JavaScript XML', 'Java Syntax Extension', 'JSON XML', 'JavaScript Extension'],
            type: 'mcq',
            correctAnswer: 0
        }
    ];

    try {
        await Question.deleteMany({});
        const createdQuestions = await Question.insertMany(sampleQuestions);
        res.status(201).json(createdQuestions);
    } catch (err) {
        res.status(400).json({ message: err.message });
    }
};

module.exports = {
    getQuestions,
    submitResult,
    seedQuestions,
    generateQuestions,
    generatePhase2Questions
};
